version: '3.7'

services:
  cgroup_executor_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: cgroup_executor_service:1
    # Extra params to entrypoint.sh go into the catchall "$@" value, which
    # are passed as extra params to gunicorn. `--reload` enables restarting
    # workers when code is changed, similar to the Django dev server.
    command: /bin/bash
    init: true
    environment:
      BLAH: 'true'
    volumes:
      - .:/src
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    ports:
#      - "8000:8000"
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
